import { StyleSheet } from "react-native";

export const MyStyles = StyleSheet.create({
  mainContainer: {
    flex: 1,
    backgroundColor: "#ece0d1",
    fontFamily: "Montserrat",
  },
  container2: {
    alignItems: "center",
    marginTop: 90,
  },
  infoBox: {
    backgroundColor: "#dbc1ac",
    position: "absolute",
    bottom: 0,
    width: "100%",
    padding: 10,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    borderWidth: 1,
    borderColor: "#634832",
  },
  infoText: {
    fontSize: 16,
    color: "#38220f",
  },
  headerRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    width: "100%",
    borderBottomWidth: 1,
    borderBottomColor: "#38220f",
    fontFamily: "Montserrat",
    marginBottom: 0,
  },
  header: {
    fontSize: 30,
    marginBottom: 5,
    color: "#38220f",
    fontFamily: "MontserratBold",
  },
  headerText: {
    color: "#38220f",
    fontSize: 20,
    marginBottom: 10,
    marginLeft: 10,
    fontFamily: "Montserrat",
    bottom: -10,
  },
  input: {
    width: 200,
    padding: 5,
    borderWidth: 1,
    borderColor: "#38220f",
    backgroundColor: "#dbc1ac",
    fontFamily: "Montserrat",
    borderRadius: 7,
  },
  roundedInput: {
    width: 200,
    padding: 5,
    paddingLeft: 15,
    borderWidth: 1,
    borderColor: "#38220f",
    backgroundColor: "#dbc1ac",
    fontFamily: "Montserrat",
    borderRadius: 50,
  },
  picker: {
    backgroundColor: "#dbc1ac",
    borderColor: "#38220f",
  },
  pickerRounded: {
    backgroundColor: "#2c382c",
    borderColor: "#cbcbcd",
  },
  buttonContainerLogout: {
    position: "absolute",
    bottom: 10,
    right: 10,
  },
  buttonStyle: {
    width: 200,
    backgroundColor: "#dbc1ac",
    borderWidth: 1,
    borderColor: "#38220f",
    borderRadius: 5,
  },
  roundedButtonStyle: {
    width: 200,
    backgroundColor: "#dbc1ac",
    borderWidth: 1,
    borderColor: "#38220f",
    borderRadius: 50,
  },
  buttonContainerReturn: {
    position: "absolute",
    top: 30,
    left: 10,
  },
  userContainer: {
    position: "absolute",
    bottom: 10,
    left: 10,
  },
  row: {
    flexDirection: "row",
    justifyContent: "space-between",
    width: "100%",
  },
  textRow: {
    color: "#634832",
    fontSize: 18,
    marginLeft: 10,
  },
  textSignedIn: {
    color: "#634832",
    fontSize: 16,
    fontFamily: "Montserrat",
  },
  errorText: {
    fontFamily: "Montserrat",
    color: "red",
    fontSize: 20,
    marginTop: 20,
    textAlign: "center",
  },
  bottomSheetText: {
    fontSize: 16,
    color: "#38220f",
    marginHorizontal: 20,
  },
  bottomView: {
    borderTopLeftRadius: 5,
    borderTopRightRadius: 5,
    position: "relative",
  },
  bottomViewPicture: {
    marginTop: 15,
    justifyContent: "center",
    alignItems: "center",
  },
  popupContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  popup: {
    flex: 1,
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: "center",
    alignItems: "center",
  },
  buttonStyleCamera: {
    backgroundColor: "rgba(0, 0, 0, 0)",
  },
});
